apiVersion: v1
kind: Service
metadata:
  name: {{ include "xin-platform.fullname" . }}-channel-gateway
  labels:
    app.kubernetes.io/name: channel-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.channelGateway.service.type }}
  selector:
    app.kubernetes.io/name: channel-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.channelGateway.service.port }}
      targetPort: http
