apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xin-platform.fullname" . }}-ingestion-worker
  labels:
    app.kubernetes.io/name: ingestion-worker
    app.kubernetes.io/component: ingestion-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- if gt (len .Values.global.annotations) 0 }}
  annotations:
    {{- range $k, $v := .Values.global.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.ingestionWorker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ingestion-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingestion-worker
        app.kubernetes.io/component: ingestion-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: ingestion-worker
          image: "{{ .Values.ingestionWorker.image.repository }}:{{ default .Chart.AppVersion .Values.ingestionWorker.image.tag }}"
          imagePullPolicy: {{ .Values.ingestionWorker.image.pullPolicy }}
          command: ["arq", "chatbot.adapters.ingestion.worker.WorkerSettings"]
          env:
            {{- range $key, $value := .Values.ingestionWorker.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- if .Values.global.otlpEndpoint }}
            - name: INGEST_OTLP_ENDPOINT
              value: {{ .Values.global.otlpEndpoint | quote }}
            {{- end }}
          envFrom:
            {{- range .Values.ingestionWorker.secretRefs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- if .Values.ingestionWorker.resources }}
          resources: {{- toYaml .Values.ingestionWorker.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.ingestionWorker.nodeSelector }}
      nodeSelector: {{- toYaml .Values.ingestionWorker.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ingestionWorker.tolerations }}
      tolerations: {{- toYaml .Values.ingestionWorker.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.ingestionWorker.affinity }}
      affinity: {{- toYaml .Values.ingestionWorker.affinity | nindent 8 }}
      {{- end }}
