apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://xin_prometheus:9090
    access: proxy
    isDefault: true

  - name: Tempo
    uid: Tempo
    type: tempo
    url: http://xin_tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus

  - name: Loki
    uid: Loki
    type: loki
    url: http://xin_loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: "trace_id=(\\w+)"
          url: "$${__value.raw}"
