server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://xin_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"
        regex: "/(.*)"
      - source_labels: ["__meta_docker_container_label_com_docker_swarm_service_name"]
        target_label: "service"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            tenant_id: tenant_id
            channel_id: channel_id
      - labels:
          tenant_id:
          channel_id:
      - timestamp:
          source: time
          format: RFC3339Nano
